### PR TITLE
project scaffolding fixes

### PR DESCRIPTION
**Pull request by willkg**
This reworks the project to have a Docker-based local dev environment, updates the README, fixes the CODE_OF_CONDUCT, moves everything from API_CHANGELOG to CHANGELOG, and updates that.

### CODE REVIEW

**Comment by willkg** [comment]
The test that's failing is due to a redesign of `/firefox/all/` on mozilla.org. I wrote that up in issue #247 .

I can't do any local development until I land this PR. I thought about trying to fix that issue in this PR along with everything else, but that's getting kind of ornery.

I'm going to land this even with the CI fail and move forward. self-r+

**Comment by leplatrem** [comment]
I'm kinda new to this project, and had to run tests locally to fix a bug.
@willkg , do you have any rationale about the benefits of docker for that kind of project? I really find it burdensome :( 

I'm tempted to think that everything could be achieved [with a simple Makefile](https://blog.mathieu-leplatre.info/tips-for-your-makefile-with-python.html), but I trust you to have good reasons, hence my curiosity :)

**Comment by willkg** [comment]
Yes. We use Docker-based local dev environments on all projects. The Docker images get used in stage and prod. This reduces differences between host operating systems and other things.

This uses a Makefile for managing things, so that you can run:

```
make build
```

and have a functional local dev environment you can use for tests, running, debugging, etc. Further, it simplifies the steps for everyone.

https://github.com/mozilla/PollBot#development

Your "simple Makefile" seems simple, but if you have developers running different kinds of systems, it's a huge pain in the ass. Are we all using the same version of Python? How much effort is it to upgrade Python versions?  Are we using what's in stage/prod? Does it have the same OS semantics? I don't that sort of thing anymore on my projects.

Hope that helps with the thinking!

I don't work on this project anymore, so feel free to make it work like other projects you and your team work on.

**Comment by bhearsum** [comment]
IMO Docker is worth the trouble, especially because many developers work on macOS, which is not the platform things like this deploy on.

**Comment by leplatrem** [comment]
Thank you both for taking the time to answer!

I think I was still holding on the possibility to debug stuff locally, but I see that you have the local folder mounted as a volume, so that seems to cover it nicely! 

I don't plan on changing anything, I was just curious :)

**Pull request merged**
