### PR TITLE
Background check doesn't impact the balrog check status.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by leplatrem** [comment]
Could you please add a quick note of explanations please?

**Comment by Natim** [comment]
Sure:

During the release flow the background rate changes it starts at 100% with the previous release then it turns to 0% then 25% then 0% then back to 100%.

This information is important but should not affect the balrog check. The balrog check verifies that the update rules si set for all platform to the right build ID.

**Comment by leplatrem** [comment]
OK

The background rate is equivalent to the uptake? If so I guess that we cover uptake already using Telemetry update parquet then...

**Comment by Natim** [comment]
> The background rate is equivalent to the uptake?

No the backgroundRate is the percentage of Firefox user that will get the update notification (and where Firefox will start downloading the update file)

**Pull request merged**
