### PR TITLE
Use Channel AURORA for devedition.

### LINKED ISSUE #176: Devedition channel should be aurora

### PR DESCRIPTION
**Pull request by Natim**
Fixes #176

### CODE REVIEW

**Comment by sylvestre** [comment]
please don't use aurora in the frontend. aurora as a product is dead. Only devedition

**Comment by Natim** [comment]
> please don't use aurora in the frontend. aurora as a product is dead. Only devedition

It is not Aurora as a product but aurora as a channel

**Comment by magopian** [comment]
@Natim is there a (simple) way to still use "beta" in pollbot instead of "aurora"? Otherwise i'll "translate" it in the delivery-dashboard.

**Comment by magopian** [comment]
I believe @sylvestre's comment is only cosmetic: whatever the _real_ channel name is, it should be _displayed_ as `devedition`.

**Pull request merged**
